export const ATUALIZAR_ANDAMENTOS_ZONAS = 'ATUALIZAR_ANDAMENTOS_ZONAS';
export const ATUALIZAR_ANDAMENTOS_POLOS = 'ATUALIZAR_ANDAMENTOS_POLOS';
export const ATUALIZAR_ANDAMENTOS_MUNICIPIOS = 'ATUALIZAR_ANDAMENTOS_MUNICPIOS';

export const ATUALIZAR_ZONAS = 'ATUALIZAR_ZONAS';
export const ATUALIZAR_POLOS = 'ATUALIZAR_POLOS';
export const ATUALIZAR_MUNICIPIOS = 'ATUALIZAR_MUNICIPIOS';

export const ATUALIZAR_NOME_ELEICAO = 'ATUALIZAR_NOME_ELEICAO';
export const ATUALIZAR_NOME_ETAPA = 'ATUALIZAR_NOME_ETAPA';
export const ATUALIZAR_DATA_ATUALIZACAO = 'ATUALIZAR_DATA_ATUALIZACAO';

export const ATUALIZAR_VISAO = 'ATUALIZAR_VISAO';
export const ATUALIZAR_ETAPA = 'ATUALIZAR_ETAPA';

export const ATUALIZAR_ETAPA_OFICIAL = 'ATUALIZAR_ETAPA_OFICIAL';
export const ATUALIZAR_POLO_SELECIONADO = 'ATUALIZAR_POLO_SELECIONADO';

export const ATUALIZAR_FILA = 'ATUALIZAR_FILA';

export const MOSTRAR_MODAL_MUNICIPIO = 'MOSTRAR_MODAL_MUNICIPIO';
export const MOSTRAR_MODAL_POLO = 'MOSTRAR_MODAL_POLO';
export const MOSTRAR_MODAL_ZONA = 'MOSTRAR_MODAL_ZONA';

export const ATUALIZAR_URL = 'ATUALIZAR_URL';
export const ATUALIZAR_ALTERNAR_ETAPAS = 'ATUALIZAR_ALTERNAR_ETAPAS';
export const ATUALIZAR_MODO_TELAO = 'ATUALIZAR_MODO_TELAO';
export const ATIVAR_NOTIFICACOES = 'ATIVAR_NOTIFICACOES';
export const ATUALIZAR_TESTE_ANDAMENTOS = 'ATUALIZAR_TESTE_ANDAMENTOS';
export const ATUALIZAR_VISAO_RECEM_ALTERADA = 'ATUALIZAR_VISAO_RECEM_ALTERADA';
export const ATUALIZAR_CICLOS = 'ATUALIZAR_CICLOS';

export const ATUALIZAR_INT_ZONAS = 'ATUALIZAR_INT_ZONAS';
export const ATUALIZAR_INT_POLOS = 'ATUALIZAR_INT_POLOS';
export const ATUALIZAR_INT_ZONAS_POLOS = 'ATUALIZAR_INT_ZONAS_POLOS';
export const ATUALIZAR_INT_MUNICIPIOS = 'ATUALIZAR_INT_MUNICIPIOS';
export const ATUALIZAR_INT_DATA = 'ATUALIZAR_INT_DATA_ATUALIZACAO';
export const ATUALIZAR_INT_ALTERNANCIA = 'ATUALIZAR_INT_ALTERNANCIA';
export const ATUALIZAR_INT_TELAO = 'ATUALIZAR_INT_TELAO';
export const ATUALIZAR_INT_FILA = 'ATUALIZAR_INT_FILA';

export const ZERAR_INTERVALOS = 'ZERAR_INTERVALOS';

export const VISAO_RAIZ = 'RAIZ';
export const VISAO_ZONAS = 'ZONAS';
export const VISAO_POLOS = 'POLOS';
export const VISAO_MUNICIPIOS = 'MUNICIPIOS';
export const VISAO_ZONASPOLO = 'ZONASPOLO';
export const VISAO_ZONASFILA = 'ZONASFILA';
export const VISAO_CONFIGURACAO = 'CONFIGURACAO';
export const VISAO_FILA = 'FILA';
export const VISAO_CONFERENCIA = 'CONFERENCIA';
